import { pgTable, text, serial, integer, boolean, decimal, timestamp, varchar, type AnyPgColumn, customType, index, unique } from "drizzle-orm/pg-core";
import { createInsertSchema } from "drizzle-zod";
import { z } from "zod";

// Custom vector type for pgvector extension
const vector = customType<{ data: number[]; driverData: string }>({
  dataType() {
    return "vector(1536)"; // OpenAI text-embedding-3-small produces 1536-dimensional vectors
  },
  toDriver(value: number[]): string {
    return JSON.stringify(value);
  },
  fromDriver(value: string): number[] {
    return JSON.parse(value);
  },
});

// Custom tsvector type for PostgreSQL full-text search
const tsvector = customType<{ data: string; driverData: string }>({
  dataType() {
    return "tsvector";
  },
  toDriver(value: string): string {
    return value;
  },
  fromDriver(value: string): string {
    return value;
  },
});

export const retailers = pgTable("retailers", {
  id: serial("id").primaryKey(),
  name: text("name").notNull(),
  logo: text("logo"),
  website: text("website"),
  isActive: boolean("is_active").default(true),
  affiliateId: varchar("affiliate_id", { length: 100 }),
  affiliateProgram: varchar("affiliate_program", { length: 50 }),
  baseAffiliateUrl: text("base_affiliate_url"),
  commissionRate: decimal("commission_rate", { precision: 4, scale: 2 }),
  affiliateStatus: varchar("affiliate_status", { length: 20 }).default("inactive"),
  affiliateConfig: text("affiliate_config"), // JSON string for configuration
});

export const products = pgTable("products", {
  id: serial("id").primaryKey(),
  name: text("name").notNull(),
  description: text("description"),
  category: text("category"),
  image: text("image"),
  brand: text("brand"),
  model: text("model"),
  embedding: vector("embedding"), // Vector embedding for semantic search
  embeddingUpdatedAt: timestamp("embedding_updated_at"), // Track when embedding was last calculated
  searchVector: tsvector("search_vector"), // Full-text search vector (auto-generated by trigger)
  createdAt: timestamp("created_at").defaultNow(),
}, (table) => ({
  // GIN index for full-text search (matches migration 0002)
  searchIdx: index("idx_products_search").using("gin", table.searchVector),
}));

export const productOffers = pgTable("product_offers", {
  id: serial("id").primaryKey(),
  productId: integer("product_id").references(() => products.id, { onDelete: 'cascade' }).notNull(),
  retailerId: integer("retailer_id").references(() => retailers.id, { onDelete: 'cascade' }).notNull(),
  price: decimal("price", { precision: 10, scale: 2 }).notNull(),
  originalPrice: decimal("original_price", { precision: 10, scale: 2 }),
  availability: text("availability").default("in_stock"), // in_stock, out_of_stock, limited_stock
  rating: decimal("rating", { precision: 2, scale: 1 }),
  reviewCount: integer("review_count").default(0),
  shippingInfo: text("shipping_info"),
  dealType: text("deal_type"), // best_price, bundle_deal, limited_time, etc.
  productUrl: text("product_url"),
  affiliateUrl: text("affiliate_url"),
  linkHealthStatus: varchar("link_health_status", { length: 20 }).default("unknown"),
  lastLinkCheck: timestamp("last_link_check"),
  clickCount: integer("click_count").default(0),
  lastUpdated: timestamp("last_updated").defaultNow(),
}, (table) => ({
  productIdIdx: index("product_offers_product_id_idx").on(table.productId),
  retailerIdIdx: index("product_offers_retailer_id_idx").on(table.retailerId),
  productRetailerIdx: index("product_offers_product_retailer_idx").on(table.productId, table.retailerId),
  availabilityIdx: index("product_offers_availability_idx").on(table.availability),
}));

// Price history tracking for historical price trends and analysis
export const priceHistory = pgTable("price_history", {
  id: serial("id").primaryKey(),
  productOfferId: integer("product_offer_id").references(() => productOffers.id, { onDelete: 'cascade' }).notNull(),
  productId: integer("product_id").references(() => products.id, { onDelete: 'cascade' }).notNull(), // Denormalized for fast queries
  retailerId: integer("retailer_id").references(() => retailers.id, { onDelete: 'cascade' }).notNull(), // Denormalized for fast queries
  price: decimal("price", { precision: 10, scale: 2 }).notNull(),
  originalPrice: decimal("original_price", { precision: 10, scale: 2 }),
  availability: text("availability"),
  rating: decimal("rating", { precision: 2, scale: 1 }),
  reviewCount: integer("review_count"),
  source: varchar("source", { length: 50 }).default("scraper"), // manual, scraper, api, admin
  confidence: decimal("confidence", { precision: 3, scale: 2 }).default("1.00"), // 0.00 to 1.00
  metadata: text("metadata"), // JSON - Additional context about price change
  recordedAt: timestamp("recorded_at").notNull(), // When this price snapshot was recorded
  createdAt: timestamp("created_at").defaultNow(),
}, (table) => ({
  // Index for querying history by product offer
  offerIdIdx: index("idx_price_history_offer_id").on(table.productOfferId, table.recordedAt),
  // Primary composite index for product price history queries (matches migration 0004)
  // Enables efficient time-series queries: WHERE product_id = X AND recorded_at > Y
  productIdIdx: index("idx_price_history_product_id").on(table.productId, table.recordedAt),
  // Index for querying history by retailer
  retailerIdIdx: index("idx_price_history_retailer_id").on(table.retailerId, table.recordedAt),
  // Index for time-series queries
  recordedAtIdx: index("idx_price_history_recorded_at").on(table.recordedAt),
}));

// Users table for authentication with Discourse-like features
export const users = pgTable("users", {
  id: serial("id").primaryKey(),
  username: varchar("username", { length: 50 }).notNull().unique(),
  email: varchar("email", { length: 255 }).notNull().unique(),
  passwordHash: varchar("password_hash", { length: 255 }).notNull(),
  role: varchar("role", { length: 20 }).default("user"),
  trustLevel: integer("trust_level").default(0), // 0-4 trust levels like Discourse
  isActive: boolean("is_active").default(true),
  isSuspended: boolean("is_suspended").default(false),
  reputation: integer("reputation").default(0),
  avatarUrl: varchar("avatar_url", { length: 500 }),
  bio: text("bio"),
  location: varchar("location", { length: 100 }),
  website: varchar("website", { length: 255 }),
  lastSeenAt: timestamp("last_seen_at"),
  postCount: integer("post_count").default(0),
  topicCount: integer("topic_count").default(0),
  likesGiven: integer("likes_given").default(0),
  likesReceived: integer("likes_received").default(0),
  timeReadPosts: integer("time_read_posts").default(0), // in seconds
  daysVisited: integer("days_visited").default(0),
  createdAt: timestamp("created_at").defaultNow(),
  updatedAt: timestamp("updated_at").defaultNow(),
});

// Password reset tokens for secure password recovery
export const passwordResetTokens = pgTable("password_reset_tokens", {
  id: serial("id").primaryKey(),
  userId: integer("user_id").references(() => users.id, { onDelete: 'cascade' }).notNull(),
  token: varchar("token", { length: 255 }).notNull().unique(),
  expiresAt: timestamp("expires_at").notNull(),
  isUsed: boolean("is_used").default(false),
  usedAt: timestamp("used_at"),
  ipAddress: varchar("ip_address", { length: 45 }), // IPv6 max length
  userAgent: varchar("user_agent", { length: 500 }),
  createdAt: timestamp("created_at").defaultNow(),
});

// Forum categories
export const forumCategories = pgTable("forum_categories", {
  id: serial("id").primaryKey(),
  name: varchar("name", { length: 100 }).notNull(),
  slug: varchar("slug", { length: 100 }).notNull().unique(),
  description: text("description"),
  color: varchar("color", { length: 7 }).default("#3b82f6"),
  icon: varchar("icon", { length: 50 }), // lucide icon name
  isActive: boolean("is_active").default(true),
  sortOrder: integer("sort_order").default(0),
  parentId: integer("parent_id").references((): AnyPgColumn => forumCategories.id, { onDelete: 'set null' }), // for subcategories
  moderatorIds: integer("moderator_ids").array(),
  createdAt: timestamp("created_at").defaultNow(),
});

// Forum topics (discussion threads)
export const forumTopics = pgTable("forum_topics", {
  id: serial("id").primaryKey(),
  title: varchar("title", { length: 255 }).notNull(),
  slug: varchar("slug", { length: 255 }).notNull(),
  content: text("content"), // Initial post content
  categoryId: integer("category_id").references(() => forumCategories.id, { onDelete: 'set null' }),
  authorId: integer("author_id").references(() => users.id, { onDelete: 'set null' }).notNull(),
  productId: integer("product_id").references(() => products.id, { onDelete: 'set null' }), // Link to products
  tags: varchar("tags", { length: 500 }).array(), // Topic tags
  isPinned: boolean("is_pinned").default(false),
  isLocked: boolean("is_locked").default(false),
  isFeatured: boolean("is_featured").default(false),
  viewCount: integer("view_count").default(0),
  postCount: integer("post_count").default(0),
  likeCount: integer("like_count").default(0),
  lastPostAt: timestamp("last_post_at"),
  createdAt: timestamp("created_at").defaultNow(),
  updatedAt: timestamp("updated_at").defaultNow(),
}, (table) => ({
  categoryIdIdx: index("forum_topics_category_id_idx").on(table.categoryId),
  authorIdIdx: index("forum_topics_author_id_idx").on(table.authorId),
  productIdIdx: index("forum_topics_product_id_idx").on(table.productId),
  createdAtIdx: index("forum_topics_created_at_idx").on(table.createdAt),
}));

// Forum posts with enhanced features
export const forumPosts = pgTable("forum_posts", {
  id: serial("id").primaryKey(),
  topicId: integer("topic_id").references(() => forumTopics.id, { onDelete: 'cascade' }).notNull(),
  authorId: integer("author_id").references(() => users.id, { onDelete: 'set null' }).notNull(),
  content: text("content").notNull(),
  rawContent: text("raw_content").notNull(), // Original markdown/text content
  isFirstPost: boolean("is_first_post").default(false),
  postNumber: integer("post_number").notNull(), // Sequential number within topic
  replyToPostId: integer("reply_to_post_id").references((): AnyPgColumn => forumPosts.id, { onDelete: 'set null' }),
  likeCount: integer("like_count").default(0),
  replyCount: integer("reply_count").default(0),
  readCount: integer("read_count").default(0),
  isHidden: boolean("is_hidden").default(false),
  hiddenReason: varchar("hidden_reason", { length: 255 }),
  editedAt: timestamp("edited_at"),
  editedById: integer("edited_by_id").references(() => users.id, { onDelete: 'set null' }),
  version: integer("version").default(1),
  createdAt: timestamp("created_at").defaultNow(),
  updatedAt: timestamp("updated_at").defaultNow(),
}, (table) => ({
  topicIdIdx: index("forum_posts_topic_id_idx").on(table.topicId),
  authorIdIdx: index("forum_posts_author_id_idx").on(table.authorId),
  createdAtIdx: index("forum_posts_created_at_idx").on(table.createdAt),
}));

// Price alerts that can notify the community
export const priceAlerts = pgTable("price_alerts", {
  id: serial("id").primaryKey(),
  userId: integer("user_id").references(() => users.id, { onDelete: 'cascade' }).notNull(),
  productId: integer("product_id").references(() => products.id, { onDelete: 'cascade' }).notNull(),
  targetPrice: decimal("target_price", { precision: 10, scale: 2 }).notNull(),
  isActive: boolean("is_active").default(true),
  notifyForum: boolean("notify_forum").default(false), // Whether to post to forum when triggered
  // Historical context
  priceWhenCreated: decimal("price_when_created", { precision: 10, scale: 2 }), // Price at creation time
  // Effectiveness tracking
  timesTriggered: integer("times_triggered").default(0), // How many times this alert has been triggered
  lastTriggeredAt: timestamp("last_triggered_at"), // When it was last triggered
  // Smart suggestions
  suggestedBySystem: boolean("suggested_by_system").default(false), // Was this suggested by the system?
  suggestionReason: text("suggestion_reason"), // Why was this suggested?
  // Metadata
  createdAt: timestamp("created_at").defaultNow(),
  updatedAt: timestamp("updated_at").defaultNow(),
}, (table) => ({
  userIdIdx: index("price_alerts_user_id_idx").on(table.userId),
  productIdIdx: index("price_alerts_product_id_idx").on(table.productId),
  isActiveIdx: index("price_alerts_is_active_idx").on(table.isActive),
}));

// Post likes/reactions
export const postLikes = pgTable("post_likes", {
  id: serial("id").primaryKey(),
  postId: integer("post_id").references(() => forumPosts.id, { onDelete: 'cascade' }).notNull(),
  userId: integer("user_id").references(() => users.id, { onDelete: 'cascade' }).notNull(),
  reactionType: varchar("reaction_type", { length: 20 }).default("like"), // like, love, laugh, etc.
  createdAt: timestamp("created_at").defaultNow(),
}, (table) => ({
  postIdIdx: index("post_likes_post_id_idx").on(table.postId),
  userIdIdx: index("post_likes_user_id_idx").on(table.userId),
}));

// User notifications
export const notifications = pgTable("notifications", {
  id: serial("id").primaryKey(),
  userId: integer("user_id").references(() => users.id, { onDelete: 'cascade' }).notNull(),
  type: varchar("type", { length: 50 }).notNull(), // mention, reply, like, price_drop, price_alert, etc.
  title: varchar("title", { length: 255 }).notNull(),
  content: text("content"),
  relatedPostId: integer("related_post_id").references(() => forumPosts.id, { onDelete: 'set null' }),
  relatedTopicId: integer("related_topic_id").references(() => forumTopics.id, { onDelete: 'set null' }),
  relatedUserId: integer("related_user_id").references(() => users.id, { onDelete: 'set null' }),
  relatedProductId: integer("related_product_id").references(() => products.id, { onDelete: 'set null' }),
  isRead: boolean("is_read").default(false),
  createdAt: timestamp("created_at").defaultNow(),
}, (table) => ({
  userIdIdx: index("notifications_user_id_idx").on(table.userId),
  userReadIdx: index("notifications_user_read_idx").on(table.userId, table.isRead),
  createdAtIdx: index("notifications_created_at_idx").on(table.createdAt),
}));

// Notification preferences for users
export const notificationPreferences = pgTable("notification_preferences", {
  id: serial("id").primaryKey(),
  userId: integer("user_id").references(() => users.id, { onDelete: 'cascade' }).notNull().unique(),
  // Price drop settings
  priceDropEnabled: boolean("price_drop_enabled").default(true),
  priceDropThresholdPercent: integer("price_drop_threshold_percent").default(10), // 10% default
  priceDropThresholdAmount: decimal("price_drop_threshold_amount", { precision: 10, scale: 2 }).default("5.00"), // $5 default
  // Alert settings
  priceAlertEnabled: boolean("price_alert_enabled").default(true),
  // Notification channels
  emailEnabled: boolean("email_enabled").default(true),
  inAppEnabled: boolean("in_app_enabled").default(true),
  // Frequency settings
  maxDailyNotifications: integer("max_daily_notifications").default(10),
  quietHoursStart: integer("quiet_hours_start"), // Hour 0-23, null = disabled
  quietHoursEnd: integer("quiet_hours_end"), // Hour 0-23, null = disabled
  // Metadata
  createdAt: timestamp("created_at").defaultNow(),
  updatedAt: timestamp("updated_at").defaultNow(),
});

// Topic tags
export const topicTags = pgTable("topic_tags", {
  id: serial("id").primaryKey(),
  name: varchar("name", { length: 50 }).notNull().unique(),
  description: text("description"),
  color: varchar("color", { length: 7 }).default("#6b7280"),
  usageCount: integer("usage_count").default(0),
  createdAt: timestamp("created_at").defaultNow(),
});

// Many-to-many relationship for topics and tags
export const topicTagRelations = pgTable("topic_tag_relations", {
  id: serial("id").primaryKey(),
  topicId: integer("topic_id").references(() => forumTopics.id, { onDelete: 'cascade' }).notNull(),
  tagId: integer("tag_id").references(() => topicTags.id, { onDelete: 'cascade' }).notNull(),
  createdAt: timestamp("created_at").defaultNow(),
}, (table) => ({
  topicIdIdx: index("topic_tag_relations_topic_id_idx").on(table.topicId),
  tagIdIdx: index("topic_tag_relations_tag_id_idx").on(table.tagId),
}));

// User mentions in posts
export const postMentions = pgTable("post_mentions", {
  id: serial("id").primaryKey(),
  postId: integer("post_id").references(() => forumPosts.id, { onDelete: 'cascade' }).notNull(),
  mentionedUserId: integer("mentioned_user_id").references(() => users.id, { onDelete: 'cascade' }).notNull(),
  mentioningUserId: integer("mentioning_user_id").references(() => users.id, { onDelete: 'cascade' }).notNull(),
  createdAt: timestamp("created_at").defaultNow(),
});

// Private messages
export const privateMessages = pgTable("private_messages", {
  id: serial("id").primaryKey(),
  senderId: integer("sender_id").references(() => users.id, { onDelete: 'set null' }).notNull(),
  recipientId: integer("recipient_id").references(() => users.id, { onDelete: 'cascade' }).notNull(),
  subject: varchar("subject", { length: 255 }).notNull(),
  content: text("content").notNull(),
  isRead: boolean("is_read").default(false),
  createdAt: timestamp("created_at").defaultNow(),
});

// User badges (achievements)
export const badges = pgTable("badges", {
  id: serial("id").primaryKey(),
  name: varchar("name", { length: 100 }).notNull(),
  description: text("description"),
  icon: varchar("icon", { length: 50 }), // lucide icon name
  color: varchar("color", { length: 7 }).default("#3b82f6"),
  type: varchar("type", { length: 20 }).notNull(), // bronze, silver, gold
  isActive: boolean("is_active").default(true),
  createdAt: timestamp("created_at").defaultNow(),
});

// User badge assignments
export const userBadges = pgTable("user_badges", {
  id: serial("id").primaryKey(),
  userId: integer("user_id").references(() => users.id, { onDelete: 'cascade' }).notNull(),
  badgeId: integer("badge_id").references(() => badges.id, { onDelete: 'cascade' }).notNull(),
  grantedAt: timestamp("granted_at").defaultNow(),
});

// Product watches - users watching products for price changes
// Watch lists for organizing watched products
export const watchLists = pgTable("watch_lists", {
  id: serial("id").primaryKey(),
  userId: integer("user_id").references(() => users.id, { onDelete: 'cascade' }).notNull(),
  name: varchar("name", { length: 255 }).notNull(),
  description: text("description"),
  color: varchar("color", { length: 7 }), // Hex color code
  icon: varchar("icon", { length: 50 }), // Icon name
  isDefault: boolean("is_default").default(false),
  sortOrder: integer("sort_order").default(0),
  createdAt: timestamp("created_at").defaultNow(),
  updatedAt: timestamp("updated_at").defaultNow(),
}, (table) => ({
  userIdIdx: index("watch_lists_user_id_idx").on(table.userId),
}));

export const productWatches = pgTable("product_watches", {
  id: serial("id").primaryKey(),
  userId: integer("user_id").references(() => users.id, { onDelete: 'cascade' }).notNull(),
  productId: integer("product_id").references(() => products.id, { onDelete: 'cascade' }).notNull(),
  watchListId: integer("watch_list_id").references(() => watchLists.id, { onDelete: 'cascade' }),
  category: varchar("category", { length: 100 }),
  notes: text("notes"),
  priority: integer("priority").default(3), // 1-5 scale
  targetPrice: decimal("target_price", { precision: 10, scale: 2 }),
  createdAt: timestamp("created_at").defaultNow(),
  updatedAt: timestamp("updated_at").defaultNow(),
}, (table) => ({
  userIdIdx: index("product_watches_user_id_idx").on(table.userId),
  productIdIdx: index("product_watches_product_id_idx").on(table.productId),
  watchListIdIdx: index("product_watches_watch_list_id_idx").on(table.watchListId),
}));

// User reputation for gamification
export const userReputation = pgTable("user_reputation", {
  id: serial("id").primaryKey(),
  userId: integer("user_id").references(() => users.id, { onDelete: 'cascade' }).notNull().unique(),
  reputationPoints: integer("reputation_points").default(0),
  dealsSpotted: integer("deals_spotted").default(0),
  accuratePredictions: integer("accurate_predictions").default(0),
  communityContributions: integer("community_contributions").default(0),
  level: integer("level").default(1),
  createdAt: timestamp("created_at").defaultNow(),
  updatedAt: timestamp("updated_at").defaultNow(),
});

// Deal spotting events for tracking who found deals
export const dealSpottings = pgTable("deal_spottings", {
  id: serial("id").primaryKey(),
  userId: integer("user_id").references(() => users.id, { onDelete: 'cascade' }).notNull(),
  productId: integer("product_id").references(() => products.id, { onDelete: 'cascade' }).notNull(),
  priceDropPercent: decimal("price_drop_percent", { precision: 5, scale: 2 }).notNull(),
  priceDropAmount: decimal("price_drop_amount", { precision: 10, scale: 2 }).notNull(),
  forumPostId: integer("forum_post_id").references(() => forumPosts.id, { onDelete: 'set null' }),
  reputationAwarded: integer("reputation_awarded").default(0),
  createdAt: timestamp("created_at").defaultNow(),
}, (table) => ({
  userIdIdx: index("deal_spottings_user_id_idx").on(table.userId),
  productIdIdx: index("deal_spottings_product_id_idx").on(table.productId),
}));

// Post revision history
export const postRevisions = pgTable("post_revisions", {
  id: serial("id").primaryKey(),
  postId: integer("post_id").references(() => forumPosts.id, { onDelete: 'cascade' }).notNull(),
  content: text("content").notNull(),
  rawContent: text("raw_content").notNull(),
  editedById: integer("edited_by_id").references(() => users.id, { onDelete: 'set null' }).notNull(),
  editReason: varchar("edit_reason", { length: 255 }),
  version: integer("version").notNull(),
  createdAt: timestamp("created_at").defaultNow(),
});

export const insertRetailerSchema = createInsertSchema(retailers).omit({
  id: true,
});

export const insertProductSchema = createInsertSchema(products).omit({
  id: true,
  createdAt: true,
}).extend({
  embedding: z.array(z.number()).optional().nullable(),
});

export const insertProductOfferSchema = createInsertSchema(productOffers).omit({
  id: true,
  lastUpdated: true,
});

export const insertPriceHistorySchema = createInsertSchema(priceHistory).omit({
  id: true,
  recordedAt: true,
  createdAt: true,
});

export const insertUserSchema = createInsertSchema(users).omit({
  id: true,
  passwordHash: true,
  createdAt: true,
  updatedAt: true,
}).extend({
  password: z.string().min(6, "Password must be at least 6 characters"),
});

export const insertPasswordResetTokenSchema = createInsertSchema(passwordResetTokens).omit({
  id: true,
  createdAt: true,
});

export const insertForumCategorySchema = createInsertSchema(forumCategories).omit({
  id: true,
  createdAt: true,
});

export const insertForumTopicSchema = createInsertSchema(forumTopics).omit({
  id: true,
  postCount: true,
  lastPostAt: true,
  createdAt: true,
  updatedAt: true,
});

export const insertForumPostSchema = createInsertSchema(forumPosts).omit({
  id: true,
  likeCount: true,
  replyCount: true,
  readCount: true,
  version: true,
  createdAt: true,
  updatedAt: true,
});

export const insertPriceAlertSchema = createInsertSchema(priceAlerts).omit({
  id: true,
  createdAt: true,
});

// New insert schemas for enhanced features
export const insertPostLikeSchema = createInsertSchema(postLikes).omit({
  id: true,
  createdAt: true,
});

export const insertNotificationSchema = createInsertSchema(notifications).omit({
  id: true,
  createdAt: true,
});

export const insertNotificationPreferencesSchema = createInsertSchema(notificationPreferences).omit({
  id: true,
  createdAt: true,
  updatedAt: true,
});

export const insertTopicTagSchema = createInsertSchema(topicTags).omit({
  id: true,
  usageCount: true,
  createdAt: true,
});

export const insertPrivateMessageSchema = createInsertSchema(privateMessages).omit({
  id: true,
  createdAt: true,
});

export const insertBadgeSchema = createInsertSchema(badges).omit({
  id: true,
  createdAt: true,
});

export const insertWatchListSchema = createInsertSchema(watchLists).omit({
  id: true,
  createdAt: true,
  updatedAt: true,
});

export const insertProductWatchSchema = createInsertSchema(productWatches).omit({
  id: true,
  createdAt: true,
  updatedAt: true,
});

export const insertUserReputationSchema = createInsertSchema(userReputation).omit({
  id: true,
  createdAt: true,
  updatedAt: true,
});

export const insertDealSpottingSchema = createInsertSchema(dealSpottings).omit({
  id: true,
  createdAt: true,
});

export const insertPostRevisionSchema = createInsertSchema(postRevisions).omit({
  id: true,
  createdAt: true,
});

// Type definitions
export type Retailer = typeof retailers.$inferSelect;
export type Product = typeof products.$inferSelect;
export type ProductOffer = typeof productOffers.$inferSelect;
export type PriceHistory = typeof priceHistory.$inferSelect;
export type User = typeof users.$inferSelect;
export type PasswordResetToken = typeof passwordResetTokens.$inferSelect;
export type ForumCategory = typeof forumCategories.$inferSelect;
export type ForumTopic = typeof forumTopics.$inferSelect;
export type ForumPost = typeof forumPosts.$inferSelect;
export type PriceAlert = typeof priceAlerts.$inferSelect;
export type PostLike = typeof postLikes.$inferSelect;
export type Notification = typeof notifications.$inferSelect;
export type NotificationPreferences = typeof notificationPreferences.$inferSelect;
export type TopicTag = typeof topicTags.$inferSelect;
export type TopicTagRelation = typeof topicTagRelations.$inferSelect;
export type PostMention = typeof postMentions.$inferSelect;
export type PrivateMessage = typeof privateMessages.$inferSelect;
export type Badge = typeof badges.$inferSelect;
export type UserBadge = typeof userBadges.$inferSelect;
export type WatchList = typeof watchLists.$inferSelect;
export type ProductWatch = typeof productWatches.$inferSelect;
export type UserReputation = typeof userReputation.$inferSelect;
export type DealSpotting = typeof dealSpottings.$inferSelect;
export type PostRevision = typeof postRevisions.$inferSelect;

export type InsertRetailer = z.infer<typeof insertRetailerSchema>;
export type InsertProduct = z.infer<typeof insertProductSchema>;
export type InsertProductOffer = z.infer<typeof insertProductOfferSchema>;
export type InsertPriceHistory = z.infer<typeof insertPriceHistorySchema>;
export type InsertUser = z.infer<typeof insertUserSchema>;
export type InsertPasswordResetToken = z.infer<typeof insertPasswordResetTokenSchema>;
export type InsertForumCategory = z.infer<typeof insertForumCategorySchema>;
export type InsertForumTopic = z.infer<typeof insertForumTopicSchema>;
export type InsertForumPost = z.infer<typeof insertForumPostSchema>;
export type InsertPriceAlert = z.infer<typeof insertPriceAlertSchema>;
export type InsertPostLike = z.infer<typeof insertPostLikeSchema>;
export type InsertNotification = z.infer<typeof insertNotificationSchema>;
export type InsertNotificationPreferences = z.infer<typeof insertNotificationPreferencesSchema>;
export type InsertTopicTag = z.infer<typeof insertTopicTagSchema>;
export type InsertPrivateMessage = z.infer<typeof insertPrivateMessageSchema>;
export type InsertBadge = z.infer<typeof insertBadgeSchema>;
export type InsertWatchList = z.infer<typeof insertWatchListSchema>;
export type InsertProductWatch = z.infer<typeof insertProductWatchSchema>;
export type InsertUserReputation = z.infer<typeof insertUserReputationSchema>;
export type InsertDealSpotting = z.infer<typeof insertDealSpottingSchema>;
export type InsertPostRevision = z.infer<typeof insertPostRevisionSchema>;

// Combined types for API responses
export type ProductWithOffers = Product & {
  offers: (ProductOffer & { retailer: Retailer })[];
  bestPrice?: number;
  savings?: number;
  savingsPercentage?: number;
  discussionCount?: number;
  hasActiveDiscussion?: boolean;
};

// Enhanced forum types with Discourse-like features
export type UserWithProfile = User & {
  badges?: (UserBadge & { badge: Badge })[];
  unreadNotifications?: number;
  trustLevelName?: string;
};

export type ForumTopicWithDetails = ForumTopic & {
  author: UserWithProfile;
  category?: ForumCategory;
  tags?: TopicTag[];
  lastPost?: ForumPost & { author: UserWithProfile };
  posts?: ForumPostWithDetails[];
  isBookmarked?: boolean;
  userCanEdit?: boolean;
  userCanDelete?: boolean;
};

export type ForumPostWithDetails = ForumPost & {
  author: UserWithProfile;
  likes?: (PostLike & { user: User })[];
  replies?: ForumPost[];
  mentions?: (PostMention & { mentionedUser: User })[];
  revisions?: PostRevision[];
  userHasLiked?: boolean;
  userCanEdit?: boolean;
  userCanDelete?: boolean;
};

export type ForumPostWithAuthor = ForumPost & {
  author: User;
};

export type NotificationWithDetails = Notification & {
  relatedUser?: User;
  relatedPost?: ForumPost;
  relatedTopic?: ForumTopic;
};

export type PrivateMessageWithUsers = PrivateMessage & {
  sender: User;
  recipient: User;
};

export type SearchFilters = {
  query?: string;
  category?: string;
  minPrice?: number;
  maxPrice?: number;
  retailers?: number[];
  minRating?: number;
  availability?: string[];
  sortBy?: "price_low" | "price_high" | "rating" | "popularity";
  page?: number;
  limit?: number;
};

// AI Scraping System Tables

// Trending products discovered by AI agents
export const trendingProducts = pgTable("trending_products", {
  id: serial("id").primaryKey(),
  name: varchar("name", { length: 255 }).notNull(),
  category: varchar("category", { length: 100 }),
  trendScore: integer("trend_score").default(0),
  searchVolume: integer("search_volume").default(0),
  source: varchar("source", { length: 50 }).notNull(), // google_trends, social_media, news
  sourceData: text("source_data"), // JSON data from source
  discoveryDate: timestamp("discovery_date").defaultNow(),
  status: varchar("status", { length: 20 }).default("discovered"), // discovered, processing, scraped, failed
  productId: integer("product_id").references(() => products.id, { onDelete: 'set null' }), // Link to created product
  createdAt: timestamp("created_at").defaultNow(),
  updatedAt: timestamp("updated_at").defaultNow(),
});

// Search queries generated by AI agents
export const searchQueries = pgTable("search_queries", {
  id: serial("id").primaryKey(),
  trendingProductId: integer("trending_product_id").references(() => trendingProducts.id, { onDelete: 'cascade' }),
  productId: integer("product_id").references(() => products.id, { onDelete: 'set null' }),
  queryText: varchar("query_text", { length: 500 }).notNull(),
  retailer: varchar("retailer", { length: 50 }),
  queryType: varchar("query_type", { length: 30 }).default("product_search"), // product_search, price_check, availability
  successRate: decimal("success_rate", { precision: 3, scale: 2 }).default("0.00"),
  avgResults: integer("avg_results").default(0),
  lastUsed: timestamp("last_used"),
  createdAt: timestamp("created_at").defaultNow(),
});

// Agent performance and session tracking
export const agentSessions = pgTable("agent_sessions", {
  id: serial("id").primaryKey(),
  agentType: varchar("agent_type", { length: 50 }).notNull(), // discovery, search, navigation, extraction, validation, coordinator
  sessionId: varchar("session_id", { length: 100 }).notNull(),
  sessionStart: timestamp("session_start").defaultNow(),
  sessionEnd: timestamp("session_end"),
  tasksCompleted: integer("tasks_completed").default(0),
  successRate: decimal("success_rate", { precision: 3, scale: 2 }).default("0.00"),
  errorsEncountered: integer("errors_encountered").default(0),
  performanceMetrics: text("performance_metrics"), // JSON data
  status: varchar("status", { length: 20 }).default("active"), // active, completed, failed
  createdAt: timestamp("created_at").defaultNow(),
});

// Scraping job management and queue
export const scrapingJobs = pgTable("scraping_jobs", {
  id: serial("id").primaryKey(),
  jobType: varchar("job_type", { length: 50 }).notNull(), // discovery, search, scrape, validate, price_update
  priority: integer("priority").default(5), // 1-10, higher = more priority
  status: varchar("status", { length: 20 }).default("pending"), // pending, running, completed, failed, retrying
  targetData: text("target_data").notNull(), // JSON with job parameters
  resultData: text("result_data"), // JSON with job results
  errorMessage: text("error_message"),
  retryCount: integer("retry_count").default(0),
  maxRetries: integer("max_retries").default(3),
  scheduledAt: timestamp("scheduled_at"),
  startedAt: timestamp("started_at"),
  completedAt: timestamp("completed_at"),
  agentSessionId: integer("agent_session_id").references(() => agentSessions.id, { onDelete: 'set null' }),
  createdAt: timestamp("created_at").defaultNow(),
  updatedAt: timestamp("updated_at").defaultNow(),
});

// Price predictions and historical analysis
export const pricePredictions = pgTable("price_predictions", {
  id: serial("id").primaryKey(),
  productOfferId: integer("product_offer_id").references(() => productOffers.id, { onDelete: 'cascade' }).notNull(),
  currentPrice: decimal("current_price", { precision: 10, scale: 2 }).notNull(),
  predictedPrice: decimal("predicted_price", { precision: 10, scale: 2 }).notNull(),
  predictionType: varchar("prediction_type", { length: 30 }).notNull(), // daily, weekly, monthly, seasonal
  confidenceScore: decimal("confidence_score", { precision: 3, scale: 2 }).notNull(),
  predictionDate: timestamp("prediction_date").notNull(),
  actualPrice: decimal("actual_price", { precision: 10, scale: 2 }), // Filled when prediction period ends
  predictionAccuracy: decimal("prediction_accuracy", { precision: 3, scale: 2 }), // Calculated after validation
  modelVersion: varchar("model_version", { length: 20 }).default("1.0"),
  createdAt: timestamp("created_at").defaultNow(),
  validatedAt: timestamp("validated_at"),
});

// Price snapshots - Daily aggregated price data
export const priceSnapshots = pgTable("price_snapshots", {
  id: serial("id").primaryKey(),
  productId: integer("product_id").references(() => products.id, { onDelete: 'cascade' }).notNull(),
  retailerId: integer("retailer_id").references(() => retailers.id, { onDelete: 'cascade' }).notNull(),
  lowestPrice: decimal("lowest_price", { precision: 10, scale: 2 }).notNull(),
  highestPrice: decimal("highest_price", { precision: 10, scale: 2 }).notNull(),
  averagePrice: decimal("average_price", { precision: 10, scale: 2 }).notNull(),
  offerCount: integer("offer_count").default(1),
  snapshotDate: timestamp("snapshot_date").notNull(), // Date of the snapshot
  createdAt: timestamp("created_at").defaultNow(),
}, (table) => ({
  productIdIdx: index("price_snapshots_product_id_idx").on(table.productId),
  retailerIdIdx: index("price_snapshots_retailer_id_idx").on(table.retailerId),
  snapshotDateIdx: index("price_snapshots_snapshot_date_idx").on(table.snapshotDate),
  productDateIdx: index("price_snapshots_product_date_idx").on(table.productId, table.snapshotDate),
}));

/**
 * Weekly price aggregates for trend analysis
 *
 * Stores aggregated price statistics per product/retailer/week combination.
 * Enables week-over-week comparison and short-term trend identification.
 *
 * @table price_aggregates_weekly
 * @unique product_id, retailer_id, year, week
 */
export const priceAggregatesWeekly = pgTable("price_aggregates_weekly", {
  id: serial("id").primaryKey(),
  productId: integer("product_id").references(() => products.id, { onDelete: "cascade" }).notNull(),
  retailerId: integer("retailer_id").references(() => retailers.id, { onDelete: "cascade" }).notNull(),
  year: integer("year").notNull(),
  week: integer("week").notNull(), // ISO week number (1-53)
  minPrice: decimal("min_price", { precision: 10, scale: 2 }).notNull(),
  maxPrice: decimal("max_price", { precision: 10, scale: 2 }).notNull(),
  avgPrice: decimal("avg_price", { precision: 10, scale: 2 }).notNull(),
  medianPrice: decimal("median_price", { precision: 10, scale: 2 }),
  volatilityScore: decimal("volatility_score", { precision: 5, scale: 2 }),
  recordCount: integer("record_count").notNull().default(0),
  weekOverWeekChange: decimal("week_over_week_change", { precision: 10, scale: 2 }),
  createdAt: timestamp("created_at").defaultNow(),
  updatedAt: timestamp("updated_at").defaultNow(),
}, (table) => ({
  productYearIdx: index("weekly_product_year_idx").on(table.productId, table.year, table.week),
  retailerYearIdx: index("weekly_retailer_year_idx").on(table.retailerId, table.year, table.week),
  createdAtIdx: index("weekly_created_idx").on(table.createdAt),
  uniqueProductRetailerWeek: unique("unique_product_retailer_week").on(table.productId, table.retailerId, table.year, table.week),
}));

/**
 * Monthly price aggregates for long-term analysis
 *
 * Stores aggregated price statistics per product/retailer/month combination.
 * Enables month-over-month and year-over-year comparisons for seasonal analysis.
 *
 * @table price_aggregates_monthly
 * @unique product_id, retailer_id, year, month
 */
export const priceAggregatesMonthly = pgTable("price_aggregates_monthly", {
  id: serial("id").primaryKey(),
  productId: integer("product_id").references(() => products.id, { onDelete: "cascade" }).notNull(),
  retailerId: integer("retailer_id").references(() => retailers.id, { onDelete: "cascade" }).notNull(),
  year: integer("year").notNull(),
  month: integer("month").notNull(), // 1-12
  minPrice: decimal("min_price", { precision: 10, scale: 2 }).notNull(),
  maxPrice: decimal("max_price", { precision: 10, scale: 2 }).notNull(),
  avgPrice: decimal("avg_price", { precision: 10, scale: 2 }).notNull(),
  medianPrice: decimal("median_price", { precision: 10, scale: 2 }),
  volatilityScore: decimal("volatility_score", { precision: 5, scale: 2 }),
  recordCount: integer("record_count").notNull().default(0),
  monthOverMonthChange: decimal("month_over_month_change", { precision: 10, scale: 2 }),
  yearOverYearChange: decimal("year_over_year_change", { precision: 10, scale: 2 }),
  createdAt: timestamp("created_at").defaultNow(),
  updatedAt: timestamp("updated_at").defaultNow(),
}, (table) => ({
  productYearIdx: index("monthly_product_year_idx").on(table.productId, table.year, table.month),
  retailerYearIdx: index("monthly_retailer_year_idx").on(table.retailerId, table.year, table.month),
  createdAtIdx: index("monthly_created_idx").on(table.createdAt),
  uniqueProductRetailerMonth: unique("unique_product_retailer_month").on(table.productId, table.retailerId, table.year, table.month),
}));

/**
 * Price trends and predictions using linear regression
 *
 * Stores calculated price trends (uptrend/downtrend/stable) with statistical
 * confidence metrics. Includes predictions for next price based on trend analysis.
 *
 * @table price_trends
 * @unique product_id, retailer_id
 */
export const priceTrends = pgTable("price_trends", {
  id: serial("id").primaryKey(),
  productId: integer("product_id").references(() => products.id, { onDelete: "cascade" }).notNull(),
  retailerId: integer("retailer_id").references(() => retailers.id, { onDelete: "cascade" }).notNull(),
  trendDirection: varchar("trend_direction", { length: 20 }).notNull(), // uptrend, downtrend, stable
  trendSlope: decimal("trend_slope", { precision: 10, scale: 4 }), // Linear regression slope ($/day)
  trendStrength: decimal("trend_strength", { precision: 5, scale: 4 }), // R² value (0-1)
  predictedNextPrice: decimal("predicted_next_price", { precision: 10, scale: 2 }),
  confidenceLevel: varchar("confidence_level", { length: 20 }), // high, medium, low
  analysisPeriodDays: integer("analysis_period_days").notNull(),
  lastAnalyzedAt: timestamp("last_analyzed_at").defaultNow(),
  createdAt: timestamp("created_at").defaultNow(),
  updatedAt: timestamp("updated_at").defaultNow(),
}, (table) => ({
  productIdx: index("trends_product_idx").on(table.productId),
  retailerIdx: index("trends_retailer_idx").on(table.retailerId),
  directionIdx: index("trends_direction_idx").on(table.trendDirection),
  analyzedIdx: index("trends_analyzed_idx").on(table.lastAnalyzedAt),
  uniqueProductRetailer: unique("unique_product_retailer_trend").on(table.productId, table.retailerId),
}));

// Scraping source configuration
export const scrapingSources = pgTable("scraping_sources", {
  id: serial("id").primaryKey(),
  name: varchar("name", { length: 100 }).notNull(),
  type: varchar("type", { length: 30 }).notNull(), // retailer, search_engine, social_media, news
  baseUrl: varchar("base_url", { length: 500 }),
  searchUrl: varchar("search_url", { length: 500 }),
  apiKey: varchar("api_key", { length: 200 }), // Encrypted API keys
  rateLimit: integer("rate_limit").default(100), // Requests per hour
  isActive: boolean("is_active").default(true),
  lastUsed: timestamp("last_used"),
  successRate: decimal("success_rate", { precision: 3, scale: 2 }).default("0.00"),
  configuration: text("configuration"), // JSON configuration for scraper
  createdAt: timestamp("created_at").defaultNow(),
  updatedAt: timestamp("updated_at").defaultNow(),
});

// Product URL tracking and validation
export const productUrls = pgTable("product_urls", {
  id: serial("id").primaryKey(),
  productId: integer("product_id").references(() => products.id, { onDelete: 'cascade' }).notNull(),
  retailerId: integer("retailer_id").references(() => retailers.id, { onDelete: 'cascade' }).notNull(),
  url: text("url").notNull(),
  urlType: varchar("url_type", { length: 30 }).default("product_page"), // product_page, search_result, api_endpoint
  isActive: boolean("is_active").default(true),
  lastChecked: timestamp("last_checked"),
  lastValidated: timestamp("last_validated"),
  validationStatus: varchar("validation_status", { length: 20 }).default("pending"), // pending, valid, invalid, changed
  responseTime: integer("response_time"), // milliseconds
  httpStatus: integer("http_status"),
  createdAt: timestamp("created_at").defaultNow(),
  updatedAt: timestamp("updated_at").defaultNow(),
});

// Job locks for preventing duplicate execution in multi-server setups
export const jobLocks = pgTable("job_locks", {
  id: serial("id").primaryKey(),
  jobName: varchar("job_name", { length: 100 }).notNull().unique(),
  lockedBy: varchar("locked_by", { length: 200 }).notNull(), // Server instance ID or hostname
  lockedAt: timestamp("locked_at").notNull().defaultNow(),
  expiresAt: timestamp("expires_at").notNull(), // Auto-release if server dies
  metadata: text("metadata"), // JSON for additional context
}, (table) => ({
  jobNameIdx: index("job_locks_name_idx").on(table.jobName),
  expiresIdx: index("job_locks_expires_idx").on(table.expiresAt),
}));

// Insert schemas for scraping tables
export const insertTrendingProductSchema = createInsertSchema(trendingProducts).omit({
  id: true,
  createdAt: true,
  updatedAt: true,
});

export const insertSearchQuerySchema = createInsertSchema(searchQueries).omit({
  id: true,
  createdAt: true,
});

export const insertAgentSessionSchema = createInsertSchema(agentSessions).omit({
  id: true,
  createdAt: true,
});

export const insertScrapingJobSchema = createInsertSchema(scrapingJobs).omit({
  id: true,
  createdAt: true,
  updatedAt: true,
});

export const insertPricePredictionSchema = createInsertSchema(pricePredictions).omit({
  id: true,
  createdAt: true,
  validatedAt: true,
});

export const insertPriceSnapshotSchema = createInsertSchema(priceSnapshots).omit({
  id: true,
  createdAt: true,
});

export const insertPriceAggregateWeeklySchema = createInsertSchema(priceAggregatesWeekly).omit({
  id: true,
  createdAt: true,
  updatedAt: true,
});

export const insertPriceAggregateMonthlySchema = createInsertSchema(priceAggregatesMonthly).omit({
  id: true,
  createdAt: true,
  updatedAt: true,
});

export const insertPriceTrendSchema = createInsertSchema(priceTrends).omit({
  id: true,
  createdAt: true,
  updatedAt: true,
  lastAnalyzedAt: true,
});

export const insertScrapingSourceSchema = createInsertSchema(scrapingSources).omit({
  id: true,
  createdAt: true,
  updatedAt: true,
});

export const insertProductUrlSchema = createInsertSchema(productUrls).omit({
  id: true,
  createdAt: true,
  updatedAt: true,
});

// Type definitions for scraping system
export type TrendingProduct = typeof trendingProducts.$inferSelect;
export type SearchQuery = typeof searchQueries.$inferSelect;
export type AgentSession = typeof agentSessions.$inferSelect;
export type ScrapingJob = typeof scrapingJobs.$inferSelect;
export type PricePrediction = typeof pricePredictions.$inferSelect;
// Note: PriceHistory and InsertPriceHistory are already defined above (lines 509, 533)
export type PriceSnapshot = typeof priceSnapshots.$inferSelect;
export type PriceAggregateWeekly = typeof priceAggregatesWeekly.$inferSelect;
export type PriceAggregateMonthly = typeof priceAggregatesMonthly.$inferSelect;
export type PriceTrend = typeof priceTrends.$inferSelect;
export type ScrapingSource = typeof scrapingSources.$inferSelect;
export type ProductUrl = typeof productUrls.$inferSelect;

export type InsertTrendingProduct = z.infer<typeof insertTrendingProductSchema>;
export type InsertSearchQuery = z.infer<typeof insertSearchQuerySchema>;
export type InsertAgentSession = z.infer<typeof insertAgentSessionSchema>;
export type InsertScrapingJob = z.infer<typeof insertScrapingJobSchema>;
export type InsertPricePrediction = z.infer<typeof insertPricePredictionSchema>;
// Note: InsertPriceHistory is already defined above (line 533)
export type InsertPriceSnapshot = z.infer<typeof insertPriceSnapshotSchema>;
export type InsertPriceAggregateWeekly = z.infer<typeof insertPriceAggregateWeeklySchema>;
export type InsertPriceAggregateMonthly = z.infer<typeof insertPriceAggregateMonthlySchema>;
export type InsertPriceTrend = z.infer<typeof insertPriceTrendSchema>;
export type InsertScrapingSource = z.infer<typeof insertScrapingSourceSchema>;
export type InsertProductUrl = z.infer<typeof insertProductUrlSchema>;

// Extended types for agent system
export type TrendingProductWithDetails = TrendingProduct & {
  queries?: SearchQuery[];
  scrapingJobs?: ScrapingJob[];
  product?: Product;
};

export type ScrapingJobWithDetails = ScrapingJob & {
  agentSession?: AgentSession;
  trendingProduct?: TrendingProduct;
};

export type AgentSessionWithJobs = AgentSession & {
  jobs?: ScrapingJob[];
  successfulJobs?: number;
  failedJobs?: number;
};

// Price history related types
export type PriceHistoryWithOffer = PriceHistory & {
  offer?: ProductOffer & {
    product?: Product;
    retailer?: Retailer;
  };
};

export type PriceSnapshotWithDetails = PriceSnapshot & {
  product?: Product;
  retailer?: Retailer;
};

export type ProductWithPriceHistory = Product & {
  priceHistory?: PriceHistory[];
  priceSnapshots?: PriceSnapshot[];
  currentLowestPrice?: number;
  priceChange24h?: number;
  priceChange7d?: number;
  priceChange30d?: number;
  allTimeLowest?: number;
  allTimeHighest?: number;
};

// Search-related types
export interface SearchSuggestion {
  query: string;
  type: 'completion' | 'correction' | 'synonym' | 'trending' | 'history' | 'suggestion';
  confidence?: number;
  description?: string;
  intent?: string;
}

export interface QueryAnalysis {
  intent: 'product_search' | 'price_comparison' | 'brand_search' | 'category_browse' | string;
  confidence: number;
  suggestions?: string[];
  category?: string;
}
